// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SnakeProtobuf.proto

package snake.network;

public final class SnakeProtobuf {
  private SnakeProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PositionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Position)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 row = 1;</code>
     */
    boolean hasRow();
    /**
     * <code>required int32 row = 1;</code>
     */
    int getRow();

    /**
     * <code>required int32 col = 2;</code>
     */
    boolean hasCol();
    /**
     * <code>required int32 col = 2;</code>
     */
    int getCol();
  }
  /**
   * Protobuf type {@code Position}
   */
  public static final class Position extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Position)
      PositionOrBuilder {
    // Use Position.newBuilder() to construct.
    private Position(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Position(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Position defaultInstance;
    public static Position getDefaultInstance() {
      return defaultInstance;
    }

    public Position getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Position(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              row_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              col_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return snake.network.SnakeProtobuf.internal_static_Position_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return snake.network.SnakeProtobuf.internal_static_Position_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              snake.network.SnakeProtobuf.Position.class, snake.network.SnakeProtobuf.Position.Builder.class);
    }

    public static com.google.protobuf.Parser<Position> PARSER =
        new com.google.protobuf.AbstractParser<Position>() {
      public Position parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Position(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Position> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ROW_FIELD_NUMBER = 1;
    private int row_;
    /**
     * <code>required int32 row = 1;</code>
     */
    public boolean hasRow() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 row = 1;</code>
     */
    public int getRow() {
      return row_;
    }

    public static final int COL_FIELD_NUMBER = 2;
    private int col_;
    /**
     * <code>required int32 col = 2;</code>
     */
    public boolean hasCol() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 col = 2;</code>
     */
    public int getCol() {
      return col_;
    }

    private void initFields() {
      row_ = 0;
      col_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRow()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCol()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, row_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, col_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, row_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, col_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static snake.network.SnakeProtobuf.Position parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static snake.network.SnakeProtobuf.Position parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static snake.network.SnakeProtobuf.Position parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static snake.network.SnakeProtobuf.Position parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static snake.network.SnakeProtobuf.Position parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static snake.network.SnakeProtobuf.Position parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static snake.network.SnakeProtobuf.Position parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static snake.network.SnakeProtobuf.Position parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static snake.network.SnakeProtobuf.Position parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static snake.network.SnakeProtobuf.Position parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(snake.network.SnakeProtobuf.Position prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Position}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Position)
        snake.network.SnakeProtobuf.PositionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return snake.network.SnakeProtobuf.internal_static_Position_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return snake.network.SnakeProtobuf.internal_static_Position_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                snake.network.SnakeProtobuf.Position.class, snake.network.SnakeProtobuf.Position.Builder.class);
      }

      // Construct using snake.network.SnakeProtobuf.Position.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        row_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        col_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return snake.network.SnakeProtobuf.internal_static_Position_descriptor;
      }

      public snake.network.SnakeProtobuf.Position getDefaultInstanceForType() {
        return snake.network.SnakeProtobuf.Position.getDefaultInstance();
      }

      public snake.network.SnakeProtobuf.Position build() {
        snake.network.SnakeProtobuf.Position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public snake.network.SnakeProtobuf.Position buildPartial() {
        snake.network.SnakeProtobuf.Position result = new snake.network.SnakeProtobuf.Position(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.row_ = row_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.col_ = col_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof snake.network.SnakeProtobuf.Position) {
          return mergeFrom((snake.network.SnakeProtobuf.Position)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(snake.network.SnakeProtobuf.Position other) {
        if (other == snake.network.SnakeProtobuf.Position.getDefaultInstance()) return this;
        if (other.hasRow()) {
          setRow(other.getRow());
        }
        if (other.hasCol()) {
          setCol(other.getCol());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRow()) {
          
          return false;
        }
        if (!hasCol()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        snake.network.SnakeProtobuf.Position parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (snake.network.SnakeProtobuf.Position) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int row_ ;
      /**
       * <code>required int32 row = 1;</code>
       */
      public boolean hasRow() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 row = 1;</code>
       */
      public int getRow() {
        return row_;
      }
      /**
       * <code>required int32 row = 1;</code>
       */
      public Builder setRow(int value) {
        bitField0_ |= 0x00000001;
        row_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 row = 1;</code>
       */
      public Builder clearRow() {
        bitField0_ = (bitField0_ & ~0x00000001);
        row_ = 0;
        onChanged();
        return this;
      }

      private int col_ ;
      /**
       * <code>required int32 col = 2;</code>
       */
      public boolean hasCol() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 col = 2;</code>
       */
      public int getCol() {
        return col_;
      }
      /**
       * <code>required int32 col = 2;</code>
       */
      public Builder setCol(int value) {
        bitField0_ |= 0x00000002;
        col_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 col = 2;</code>
       */
      public Builder clearCol() {
        bitField0_ = (bitField0_ & ~0x00000002);
        col_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Position)
    }

    static {
      defaultInstance = new Position(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Position)
  }

  public interface SnakeMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SnakeMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 frameCount = 1;</code>
     */
    boolean hasFrameCount();
    /**
     * <code>required int32 frameCount = 1;</code>
     */
    int getFrameCount();

    /**
     * <code>required string UUID = 2;</code>
     */
    boolean hasUUID();
    /**
     * <code>required string UUID = 2;</code>
     */
    java.lang.String getUUID();
    /**
     * <code>required string UUID = 2;</code>
     */
    com.google.protobuf.ByteString
        getUUIDBytes();

    /**
     * <code>repeated .Position snakePartList = 3;</code>
     */
    java.util.List<snake.network.SnakeProtobuf.Position> 
        getSnakePartListList();
    /**
     * <code>repeated .Position snakePartList = 3;</code>
     */
    snake.network.SnakeProtobuf.Position getSnakePartList(int index);
    /**
     * <code>repeated .Position snakePartList = 3;</code>
     */
    int getSnakePartListCount();
    /**
     * <code>repeated .Position snakePartList = 3;</code>
     */
    java.util.List<? extends snake.network.SnakeProtobuf.PositionOrBuilder> 
        getSnakePartListOrBuilderList();
    /**
     * <code>repeated .Position snakePartList = 3;</code>
     */
    snake.network.SnakeProtobuf.PositionOrBuilder getSnakePartListOrBuilder(
        int index);

    /**
     * <code>required int32 avgDelay = 4;</code>
     */
    boolean hasAvgDelay();
    /**
     * <code>required int32 avgDelay = 4;</code>
     */
    int getAvgDelay();

    /**
     * <code>optional .Position applePosition = 5;</code>
     */
    boolean hasApplePosition();
    /**
     * <code>optional .Position applePosition = 5;</code>
     */
    snake.network.SnakeProtobuf.Position getApplePosition();
    /**
     * <code>optional .Position applePosition = 5;</code>
     */
    snake.network.SnakeProtobuf.PositionOrBuilder getApplePositionOrBuilder();
  }
  /**
   * Protobuf type {@code SnakeMsg}
   */
  public static final class SnakeMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:SnakeMsg)
      SnakeMsgOrBuilder {
    // Use SnakeMsg.newBuilder() to construct.
    private SnakeMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SnakeMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SnakeMsg defaultInstance;
    public static SnakeMsg getDefaultInstance() {
      return defaultInstance;
    }

    public SnakeMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SnakeMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              frameCount_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              uUID_ = bs;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                snakePartList_ = new java.util.ArrayList<snake.network.SnakeProtobuf.Position>();
                mutable_bitField0_ |= 0x00000004;
              }
              snakePartList_.add(input.readMessage(snake.network.SnakeProtobuf.Position.PARSER, extensionRegistry));
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              avgDelay_ = input.readInt32();
              break;
            }
            case 42: {
              snake.network.SnakeProtobuf.Position.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = applePosition_.toBuilder();
              }
              applePosition_ = input.readMessage(snake.network.SnakeProtobuf.Position.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(applePosition_);
                applePosition_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          snakePartList_ = java.util.Collections.unmodifiableList(snakePartList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return snake.network.SnakeProtobuf.internal_static_SnakeMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return snake.network.SnakeProtobuf.internal_static_SnakeMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              snake.network.SnakeProtobuf.SnakeMsg.class, snake.network.SnakeProtobuf.SnakeMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<SnakeMsg> PARSER =
        new com.google.protobuf.AbstractParser<SnakeMsg>() {
      public SnakeMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SnakeMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SnakeMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FRAMECOUNT_FIELD_NUMBER = 1;
    private int frameCount_;
    /**
     * <code>required int32 frameCount = 1;</code>
     */
    public boolean hasFrameCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 frameCount = 1;</code>
     */
    public int getFrameCount() {
      return frameCount_;
    }

    public static final int UUID_FIELD_NUMBER = 2;
    private java.lang.Object uUID_;
    /**
     * <code>required string UUID = 2;</code>
     */
    public boolean hasUUID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string UUID = 2;</code>
     */
    public java.lang.String getUUID() {
      java.lang.Object ref = uUID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uUID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string UUID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUUIDBytes() {
      java.lang.Object ref = uUID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uUID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SNAKEPARTLIST_FIELD_NUMBER = 3;
    private java.util.List<snake.network.SnakeProtobuf.Position> snakePartList_;
    /**
     * <code>repeated .Position snakePartList = 3;</code>
     */
    public java.util.List<snake.network.SnakeProtobuf.Position> getSnakePartListList() {
      return snakePartList_;
    }
    /**
     * <code>repeated .Position snakePartList = 3;</code>
     */
    public java.util.List<? extends snake.network.SnakeProtobuf.PositionOrBuilder> 
        getSnakePartListOrBuilderList() {
      return snakePartList_;
    }
    /**
     * <code>repeated .Position snakePartList = 3;</code>
     */
    public int getSnakePartListCount() {
      return snakePartList_.size();
    }
    /**
     * <code>repeated .Position snakePartList = 3;</code>
     */
    public snake.network.SnakeProtobuf.Position getSnakePartList(int index) {
      return snakePartList_.get(index);
    }
    /**
     * <code>repeated .Position snakePartList = 3;</code>
     */
    public snake.network.SnakeProtobuf.PositionOrBuilder getSnakePartListOrBuilder(
        int index) {
      return snakePartList_.get(index);
    }

    public static final int AVGDELAY_FIELD_NUMBER = 4;
    private int avgDelay_;
    /**
     * <code>required int32 avgDelay = 4;</code>
     */
    public boolean hasAvgDelay() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 avgDelay = 4;</code>
     */
    public int getAvgDelay() {
      return avgDelay_;
    }

    public static final int APPLEPOSITION_FIELD_NUMBER = 5;
    private snake.network.SnakeProtobuf.Position applePosition_;
    /**
     * <code>optional .Position applePosition = 5;</code>
     */
    public boolean hasApplePosition() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Position applePosition = 5;</code>
     */
    public snake.network.SnakeProtobuf.Position getApplePosition() {
      return applePosition_;
    }
    /**
     * <code>optional .Position applePosition = 5;</code>
     */
    public snake.network.SnakeProtobuf.PositionOrBuilder getApplePositionOrBuilder() {
      return applePosition_;
    }

    private void initFields() {
      frameCount_ = 0;
      uUID_ = "";
      snakePartList_ = java.util.Collections.emptyList();
      avgDelay_ = 0;
      applePosition_ = snake.network.SnakeProtobuf.Position.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFrameCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUUID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAvgDelay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getSnakePartListCount(); i++) {
        if (!getSnakePartList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasApplePosition()) {
        if (!getApplePosition().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, frameCount_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUUIDBytes());
      }
      for (int i = 0; i < snakePartList_.size(); i++) {
        output.writeMessage(3, snakePartList_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, avgDelay_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(5, applePosition_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, frameCount_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUUIDBytes());
      }
      for (int i = 0; i < snakePartList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, snakePartList_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, avgDelay_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, applePosition_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static snake.network.SnakeProtobuf.SnakeMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static snake.network.SnakeProtobuf.SnakeMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static snake.network.SnakeProtobuf.SnakeMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static snake.network.SnakeProtobuf.SnakeMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static snake.network.SnakeProtobuf.SnakeMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static snake.network.SnakeProtobuf.SnakeMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static snake.network.SnakeProtobuf.SnakeMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static snake.network.SnakeProtobuf.SnakeMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static snake.network.SnakeProtobuf.SnakeMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static snake.network.SnakeProtobuf.SnakeMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(snake.network.SnakeProtobuf.SnakeMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SnakeMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SnakeMsg)
        snake.network.SnakeProtobuf.SnakeMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return snake.network.SnakeProtobuf.internal_static_SnakeMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return snake.network.SnakeProtobuf.internal_static_SnakeMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                snake.network.SnakeProtobuf.SnakeMsg.class, snake.network.SnakeProtobuf.SnakeMsg.Builder.class);
      }

      // Construct using snake.network.SnakeProtobuf.SnakeMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSnakePartListFieldBuilder();
          getApplePositionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        frameCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        uUID_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (snakePartListBuilder_ == null) {
          snakePartList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          snakePartListBuilder_.clear();
        }
        avgDelay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (applePositionBuilder_ == null) {
          applePosition_ = snake.network.SnakeProtobuf.Position.getDefaultInstance();
        } else {
          applePositionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return snake.network.SnakeProtobuf.internal_static_SnakeMsg_descriptor;
      }

      public snake.network.SnakeProtobuf.SnakeMsg getDefaultInstanceForType() {
        return snake.network.SnakeProtobuf.SnakeMsg.getDefaultInstance();
      }

      public snake.network.SnakeProtobuf.SnakeMsg build() {
        snake.network.SnakeProtobuf.SnakeMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public snake.network.SnakeProtobuf.SnakeMsg buildPartial() {
        snake.network.SnakeProtobuf.SnakeMsg result = new snake.network.SnakeProtobuf.SnakeMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.frameCount_ = frameCount_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uUID_ = uUID_;
        if (snakePartListBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            snakePartList_ = java.util.Collections.unmodifiableList(snakePartList_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.snakePartList_ = snakePartList_;
        } else {
          result.snakePartList_ = snakePartListBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.avgDelay_ = avgDelay_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        if (applePositionBuilder_ == null) {
          result.applePosition_ = applePosition_;
        } else {
          result.applePosition_ = applePositionBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof snake.network.SnakeProtobuf.SnakeMsg) {
          return mergeFrom((snake.network.SnakeProtobuf.SnakeMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(snake.network.SnakeProtobuf.SnakeMsg other) {
        if (other == snake.network.SnakeProtobuf.SnakeMsg.getDefaultInstance()) return this;
        if (other.hasFrameCount()) {
          setFrameCount(other.getFrameCount());
        }
        if (other.hasUUID()) {
          bitField0_ |= 0x00000002;
          uUID_ = other.uUID_;
          onChanged();
        }
        if (snakePartListBuilder_ == null) {
          if (!other.snakePartList_.isEmpty()) {
            if (snakePartList_.isEmpty()) {
              snakePartList_ = other.snakePartList_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureSnakePartListIsMutable();
              snakePartList_.addAll(other.snakePartList_);
            }
            onChanged();
          }
        } else {
          if (!other.snakePartList_.isEmpty()) {
            if (snakePartListBuilder_.isEmpty()) {
              snakePartListBuilder_.dispose();
              snakePartListBuilder_ = null;
              snakePartList_ = other.snakePartList_;
              bitField0_ = (bitField0_ & ~0x00000004);
              snakePartListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSnakePartListFieldBuilder() : null;
            } else {
              snakePartListBuilder_.addAllMessages(other.snakePartList_);
            }
          }
        }
        if (other.hasAvgDelay()) {
          setAvgDelay(other.getAvgDelay());
        }
        if (other.hasApplePosition()) {
          mergeApplePosition(other.getApplePosition());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFrameCount()) {
          
          return false;
        }
        if (!hasUUID()) {
          
          return false;
        }
        if (!hasAvgDelay()) {
          
          return false;
        }
        for (int i = 0; i < getSnakePartListCount(); i++) {
          if (!getSnakePartList(i).isInitialized()) {
            
            return false;
          }
        }
        if (hasApplePosition()) {
          if (!getApplePosition().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        snake.network.SnakeProtobuf.SnakeMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (snake.network.SnakeProtobuf.SnakeMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int frameCount_ ;
      /**
       * <code>required int32 frameCount = 1;</code>
       */
      public boolean hasFrameCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 frameCount = 1;</code>
       */
      public int getFrameCount() {
        return frameCount_;
      }
      /**
       * <code>required int32 frameCount = 1;</code>
       */
      public Builder setFrameCount(int value) {
        bitField0_ |= 0x00000001;
        frameCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 frameCount = 1;</code>
       */
      public Builder clearFrameCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        frameCount_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object uUID_ = "";
      /**
       * <code>required string UUID = 2;</code>
       */
      public boolean hasUUID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string UUID = 2;</code>
       */
      public java.lang.String getUUID() {
        java.lang.Object ref = uUID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uUID_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string UUID = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUUIDBytes() {
        java.lang.Object ref = uUID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uUID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string UUID = 2;</code>
       */
      public Builder setUUID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uUID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string UUID = 2;</code>
       */
      public Builder clearUUID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uUID_ = getDefaultInstance().getUUID();
        onChanged();
        return this;
      }
      /**
       * <code>required string UUID = 2;</code>
       */
      public Builder setUUIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uUID_ = value;
        onChanged();
        return this;
      }

      private java.util.List<snake.network.SnakeProtobuf.Position> snakePartList_ =
        java.util.Collections.emptyList();
      private void ensureSnakePartListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          snakePartList_ = new java.util.ArrayList<snake.network.SnakeProtobuf.Position>(snakePartList_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          snake.network.SnakeProtobuf.Position, snake.network.SnakeProtobuf.Position.Builder, snake.network.SnakeProtobuf.PositionOrBuilder> snakePartListBuilder_;

      /**
       * <code>repeated .Position snakePartList = 3;</code>
       */
      public java.util.List<snake.network.SnakeProtobuf.Position> getSnakePartListList() {
        if (snakePartListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(snakePartList_);
        } else {
          return snakePartListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Position snakePartList = 3;</code>
       */
      public int getSnakePartListCount() {
        if (snakePartListBuilder_ == null) {
          return snakePartList_.size();
        } else {
          return snakePartListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Position snakePartList = 3;</code>
       */
      public snake.network.SnakeProtobuf.Position getSnakePartList(int index) {
        if (snakePartListBuilder_ == null) {
          return snakePartList_.get(index);
        } else {
          return snakePartListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Position snakePartList = 3;</code>
       */
      public Builder setSnakePartList(
          int index, snake.network.SnakeProtobuf.Position value) {
        if (snakePartListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSnakePartListIsMutable();
          snakePartList_.set(index, value);
          onChanged();
        } else {
          snakePartListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Position snakePartList = 3;</code>
       */
      public Builder setSnakePartList(
          int index, snake.network.SnakeProtobuf.Position.Builder builderForValue) {
        if (snakePartListBuilder_ == null) {
          ensureSnakePartListIsMutable();
          snakePartList_.set(index, builderForValue.build());
          onChanged();
        } else {
          snakePartListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Position snakePartList = 3;</code>
       */
      public Builder addSnakePartList(snake.network.SnakeProtobuf.Position value) {
        if (snakePartListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSnakePartListIsMutable();
          snakePartList_.add(value);
          onChanged();
        } else {
          snakePartListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Position snakePartList = 3;</code>
       */
      public Builder addSnakePartList(
          int index, snake.network.SnakeProtobuf.Position value) {
        if (snakePartListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSnakePartListIsMutable();
          snakePartList_.add(index, value);
          onChanged();
        } else {
          snakePartListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Position snakePartList = 3;</code>
       */
      public Builder addSnakePartList(
          snake.network.SnakeProtobuf.Position.Builder builderForValue) {
        if (snakePartListBuilder_ == null) {
          ensureSnakePartListIsMutable();
          snakePartList_.add(builderForValue.build());
          onChanged();
        } else {
          snakePartListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Position snakePartList = 3;</code>
       */
      public Builder addSnakePartList(
          int index, snake.network.SnakeProtobuf.Position.Builder builderForValue) {
        if (snakePartListBuilder_ == null) {
          ensureSnakePartListIsMutable();
          snakePartList_.add(index, builderForValue.build());
          onChanged();
        } else {
          snakePartListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Position snakePartList = 3;</code>
       */
      public Builder addAllSnakePartList(
          java.lang.Iterable<? extends snake.network.SnakeProtobuf.Position> values) {
        if (snakePartListBuilder_ == null) {
          ensureSnakePartListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, snakePartList_);
          onChanged();
        } else {
          snakePartListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Position snakePartList = 3;</code>
       */
      public Builder clearSnakePartList() {
        if (snakePartListBuilder_ == null) {
          snakePartList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          snakePartListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Position snakePartList = 3;</code>
       */
      public Builder removeSnakePartList(int index) {
        if (snakePartListBuilder_ == null) {
          ensureSnakePartListIsMutable();
          snakePartList_.remove(index);
          onChanged();
        } else {
          snakePartListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Position snakePartList = 3;</code>
       */
      public snake.network.SnakeProtobuf.Position.Builder getSnakePartListBuilder(
          int index) {
        return getSnakePartListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Position snakePartList = 3;</code>
       */
      public snake.network.SnakeProtobuf.PositionOrBuilder getSnakePartListOrBuilder(
          int index) {
        if (snakePartListBuilder_ == null) {
          return snakePartList_.get(index);  } else {
          return snakePartListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Position snakePartList = 3;</code>
       */
      public java.util.List<? extends snake.network.SnakeProtobuf.PositionOrBuilder> 
           getSnakePartListOrBuilderList() {
        if (snakePartListBuilder_ != null) {
          return snakePartListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(snakePartList_);
        }
      }
      /**
       * <code>repeated .Position snakePartList = 3;</code>
       */
      public snake.network.SnakeProtobuf.Position.Builder addSnakePartListBuilder() {
        return getSnakePartListFieldBuilder().addBuilder(
            snake.network.SnakeProtobuf.Position.getDefaultInstance());
      }
      /**
       * <code>repeated .Position snakePartList = 3;</code>
       */
      public snake.network.SnakeProtobuf.Position.Builder addSnakePartListBuilder(
          int index) {
        return getSnakePartListFieldBuilder().addBuilder(
            index, snake.network.SnakeProtobuf.Position.getDefaultInstance());
      }
      /**
       * <code>repeated .Position snakePartList = 3;</code>
       */
      public java.util.List<snake.network.SnakeProtobuf.Position.Builder> 
           getSnakePartListBuilderList() {
        return getSnakePartListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          snake.network.SnakeProtobuf.Position, snake.network.SnakeProtobuf.Position.Builder, snake.network.SnakeProtobuf.PositionOrBuilder> 
          getSnakePartListFieldBuilder() {
        if (snakePartListBuilder_ == null) {
          snakePartListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              snake.network.SnakeProtobuf.Position, snake.network.SnakeProtobuf.Position.Builder, snake.network.SnakeProtobuf.PositionOrBuilder>(
                  snakePartList_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          snakePartList_ = null;
        }
        return snakePartListBuilder_;
      }

      private int avgDelay_ ;
      /**
       * <code>required int32 avgDelay = 4;</code>
       */
      public boolean hasAvgDelay() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 avgDelay = 4;</code>
       */
      public int getAvgDelay() {
        return avgDelay_;
      }
      /**
       * <code>required int32 avgDelay = 4;</code>
       */
      public Builder setAvgDelay(int value) {
        bitField0_ |= 0x00000008;
        avgDelay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 avgDelay = 4;</code>
       */
      public Builder clearAvgDelay() {
        bitField0_ = (bitField0_ & ~0x00000008);
        avgDelay_ = 0;
        onChanged();
        return this;
      }

      private snake.network.SnakeProtobuf.Position applePosition_ = snake.network.SnakeProtobuf.Position.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          snake.network.SnakeProtobuf.Position, snake.network.SnakeProtobuf.Position.Builder, snake.network.SnakeProtobuf.PositionOrBuilder> applePositionBuilder_;
      /**
       * <code>optional .Position applePosition = 5;</code>
       */
      public boolean hasApplePosition() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .Position applePosition = 5;</code>
       */
      public snake.network.SnakeProtobuf.Position getApplePosition() {
        if (applePositionBuilder_ == null) {
          return applePosition_;
        } else {
          return applePositionBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Position applePosition = 5;</code>
       */
      public Builder setApplePosition(snake.network.SnakeProtobuf.Position value) {
        if (applePositionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          applePosition_ = value;
          onChanged();
        } else {
          applePositionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .Position applePosition = 5;</code>
       */
      public Builder setApplePosition(
          snake.network.SnakeProtobuf.Position.Builder builderForValue) {
        if (applePositionBuilder_ == null) {
          applePosition_ = builderForValue.build();
          onChanged();
        } else {
          applePositionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .Position applePosition = 5;</code>
       */
      public Builder mergeApplePosition(snake.network.SnakeProtobuf.Position value) {
        if (applePositionBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              applePosition_ != snake.network.SnakeProtobuf.Position.getDefaultInstance()) {
            applePosition_ =
              snake.network.SnakeProtobuf.Position.newBuilder(applePosition_).mergeFrom(value).buildPartial();
          } else {
            applePosition_ = value;
          }
          onChanged();
        } else {
          applePositionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .Position applePosition = 5;</code>
       */
      public Builder clearApplePosition() {
        if (applePositionBuilder_ == null) {
          applePosition_ = snake.network.SnakeProtobuf.Position.getDefaultInstance();
          onChanged();
        } else {
          applePositionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .Position applePosition = 5;</code>
       */
      public snake.network.SnakeProtobuf.Position.Builder getApplePositionBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getApplePositionFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Position applePosition = 5;</code>
       */
      public snake.network.SnakeProtobuf.PositionOrBuilder getApplePositionOrBuilder() {
        if (applePositionBuilder_ != null) {
          return applePositionBuilder_.getMessageOrBuilder();
        } else {
          return applePosition_;
        }
      }
      /**
       * <code>optional .Position applePosition = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          snake.network.SnakeProtobuf.Position, snake.network.SnakeProtobuf.Position.Builder, snake.network.SnakeProtobuf.PositionOrBuilder> 
          getApplePositionFieldBuilder() {
        if (applePositionBuilder_ == null) {
          applePositionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              snake.network.SnakeProtobuf.Position, snake.network.SnakeProtobuf.Position.Builder, snake.network.SnakeProtobuf.PositionOrBuilder>(
                  getApplePosition(),
                  getParentForChildren(),
                  isClean());
          applePosition_ = null;
        }
        return applePositionBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:SnakeMsg)
    }

    static {
      defaultInstance = new SnakeMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SnakeMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Position_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Position_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SnakeMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SnakeMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023SnakeProtobuf.proto\"$\n\010Position\022\013\n\003row" +
      "\030\001 \002(\005\022\013\n\003col\030\002 \002(\005\"\202\001\n\010SnakeMsg\022\022\n\nfram" +
      "eCount\030\001 \002(\005\022\014\n\004UUID\030\002 \002(\t\022 \n\rsnakePartL" +
      "ist\030\003 \003(\0132\t.Position\022\020\n\010avgDelay\030\004 \002(\005\022 " +
      "\n\rapplePosition\030\005 \001(\0132\t.PositionB\017\n\rsnak" +
      "e.network"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Position_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Position_descriptor,
        new java.lang.String[] { "Row", "Col", });
    internal_static_SnakeMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SnakeMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SnakeMsg_descriptor,
        new java.lang.String[] { "FrameCount", "UUID", "SnakePartList", "AvgDelay", "ApplePosition", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
